### ISSUE TITLE
Project icon?

### ISSUE THREAD

**Issue by crcastle** [nickromano/product-release-notes#1]
Hey @nickromano, this is a really cool little project.  Any thoughts on an icon for it?  I'm looking at featuring it in Heroku's monthly newsletter.

**Comment by nickromano** [comment]
Hi, @crcastle that would be awesome thank you!  I'll put an icon together today.  Please let me know if there is any copy or anything else you would need!

Nick

**Comment by nickromano** [comment]
Added an icon to the project:

https://github.com/nickromano/product-release-notes/blob/master/docs/logo.svg

https://github.com/nickromano/product-release-notes/blob/master/README.md

Thank you!

**Comment by crcastle** [comment]
Awesome.  Thanks Nick!  I think we're good on copy.  I'll write-up a couple sentences and include the logo and the Heroku Button in the newsletter.
